services:
  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: airflow-init
    depends_on:
      - postgres-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_USER_HOME_DIR=/opt/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow users create \
          -u admin \
          -f Admin \
          -l User \
          -r Admin \
          -e admin@example.org \
          -p admin
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    
  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres-airflow
      - airflow-init
    ports:
      - "8081:8080" 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=itsAsecret!!
      - AIRFLOW_USER_HOME_DIR=/opt/airflow
    command: airflow webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres-airflow
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_USER_HOME_DIR=/opt/airflow
    command: airflow scheduler
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  kafka-cli:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-cli
    depends_on:
      - zookeeper
      - kafka
    entrypoint: /bin/bash
    tty: true


  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode:/hadoop/dfs/name
      - hadoop_conf:/opt/hadoop/conf  
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - datanode:/hadoop/dfs/data
      - hadoop_conf:/opt/hadoop/conf  
    depends_on:
      - namenode

  spark-master:
    image: apache/spark:3.5.0
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000  
      - HADOOP_CONF_DIR=/opt/hadoop/conf  
    volumes:
      - hadoop_conf:/opt/hadoop/conf 
    depends_on:
      - namenode
      - datanode
      - kafka

  spark-worker:
    image: apache/spark:3.5.0
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000 
      - HADOOP_CONF_DIR=/opt/hadoop/conf 
    volumes:
      - hadoop_conf:/opt/hadoop/conf  
    depends_on:
      - spark-master

  model-service:
    build: ./model_service
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - INPUT_TOPIC=credit_events
      - OUTPUT_TOPIC=predictions
      - WINDOW_SIZE=21
      - REDIS_HOST=redis
      # - MODEL_PATH=/models/credit_model.joblib
      - FEATURES_PATH=/models/model_features.json
    volumes:
      - ./model_service:/app
      # - ./model_service:/models
    depends_on:
      - kafka
      - redis

  kafka-producer:
    build: ./kafka-producer
    environment:                           
      - ./kafka-producer-state:/app/state
    depends_on:
      - kafka
    
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prediction_saver:
    build: ./prediction_saver
    container_name: prediction_saver
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - INPUT_TOPIC=predictions
      - REDIS_HOST=redis

  historical-service:
    build: ./historical_service
    container_name: historical-service
    ports:
      - "8001:8001" 
    environment:
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000
      - HADOOP_CONF_DIR=/opt/hadoop/conf
    volumes:
      - hadoop_conf:/opt/hadoop/conf 
    depends_on:
      - namenode
      - datanode
      - spark-master
    networks:
      - default

volumes:
  namenode:
  datanode:
  hadoop_conf: 
  kafka-producer-state: {}
  postgres_db:
  redis_data:

networks:
  default:
    name: financial-risk_default